/** Nazioni per società straniere: Europa + principali nazioni rugby */
export const RUGBY_CLUB_COUNTRIES = [
  'Albania',
  'Andorra',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaigian',
  'Bielorussia',
  'Belgio',
  'Bosnia ed Erzegovina',
  'Brasile',
  'Bulgaria',
  'Canada',
  'Cile',
  'Cipro',
  'Croazia',
  'Danimarca',
  'Estonia',
  'Fiji',
  'Finlandia',
  'Francia',
  'Galles',
  'Georgia',
  'Germania',
  'Giappone',
  'Grecia',
  'Inghilterra',
  'Irlanda',
  'Islanda',
  'Kazakistan',
  'Kenya',
  'Kosovo',
  'Lettonia',
  'Liechtenstein',
  'Lituania',
  'Lussemburgo',
  'Malta',
  'Moldavia',
  'Monaco',
  'Montenegro',
  'Norvegia',
  'Nuova Zelanda',
  'Paesi Bassi',
  'Polonia',
  'Portogallo',
  'Repubblica Ceca',
  'Romania',
  'Russia',
  'San Marino',
  'Samoa',
  'Scozia',
  'Serbia',
  'Slovacchia',
  'Slovenia',
  'Spagna',
  'Stati Uniti',
  'Svezia',
  'Svizzera',
  'Tonga',
  'Turchia',
  'Ucraina',
  'Ungheria',
  'Vaticano',
] as const

export type RugbyClubCountry = (typeof RUGBY_CLUB_COUNTRIES)[number]
